# Default configuration
cockroachdb:
  enabled: true
  # See https://github.com/cockroachdb/helm-charts/blob/master/cockroachdb/values.yaml
  image:
    repository: cockroachdb/cockroach
  tls:
    certs:
      provided: true
      nodeSecret: cockroachdb.node
      clientRootSecret: cockroachdb.client.root
      selfSigner:
        enabled: false
  ingress:
    enabled: false

yugabyte:
  enabled: false
  Image:
    repository: yugabytedb/yugabyte

  # See https://github.com/yugabyte/charts/blob/master/stable/yugabyte/values.yaml
