// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pkg/models/modelspb/models.proto

package modelspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CellUnion is a delta-encoded list of S2 cell IDs:
// cells[0] = first_cell, cells[i] = cells[i-1] + (deltas[i-1] << delta_shift).
type CellUnion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstCell     uint64                 `protobuf:"fixed64,1,opt,name=first_cell,json=firstCell,proto3" json:"first_cell,omitempty"`
	DeltaShift    uint32                 `protobuf:"varint,2,opt,name=delta_shift,json=deltaShift,proto3" json:"delta_shift,omitempty"`
	Deltas        []int64                `protobuf:"zigzag64,3,rep,packed,name=deltas,proto3" json:"deltas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CellUnion) Reset() {
	*x = CellUnion{}
	mi := &file_pkg_models_modelspb_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CellUnion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellUnion) ProtoMessage() {}

func (x *CellUnion) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_models_modelspb_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellUnion.ProtoReflect.Descriptor instead.
func (*CellUnion) Descriptor() ([]byte, []int) {
	return file_pkg_models_modelspb_models_proto_rawDescGZIP(), []int{0}
}

func (x *CellUnion) GetFirstCell() uint64 {
	if x != nil {
		return x.FirstCell
	}
	return 0
}

func (x *CellUnion) GetDeltaShift() uint32 {
	if x != nil {
		return x.DeltaShift
	}
	return 0
}

func (x *CellUnion) GetDeltas() []int64 {
	if x != nil {
		return x.Deltas
	}
	return nil
}

type CellsVolume4D struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cells         *CellUnion             `protobuf:"bytes,1,opt,name=cells,proto3" json:"cells,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	AltitudeLo    *float32               `protobuf:"fixed32,4,opt,name=altitude_lo,json=altitudeLo,proto3,oneof" json:"altitude_lo,omitempty"`
	AltitudeHi    *float32               `protobuf:"fixed32,5,opt,name=altitude_hi,json=altitudeHi,proto3,oneof" json:"altitude_hi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CellsVolume4D) Reset() {
	*x = CellsVolume4D{}
	mi := &file_pkg_models_modelspb_models_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CellsVolume4D) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellsVolume4D) ProtoMessage() {}

func (x *CellsVolume4D) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_models_modelspb_models_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellsVolume4D.ProtoReflect.Descriptor instead.
func (*CellsVolume4D) Descriptor() ([]byte, []int) {
	return file_pkg_models_modelspb_models_proto_rawDescGZIP(), []int{1}
}

func (x *CellsVolume4D) GetCells() *CellUnion {
	if x != nil {
		return x.Cells
	}
	return nil
}

func (x *CellsVolume4D) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *CellsVolume4D) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *CellsVolume4D) GetAltitudeLo() float32 {
	if x != nil && x.AltitudeLo != nil {
		return *x.AltitudeLo
	}
	return 0
}

func (x *CellsVolume4D) GetAltitudeHi() float32 {
	if x != nil && x.AltitudeHi != nil {
		return *x.AltitudeHi
	}
	return 0
}

var File_pkg_models_modelspb_models_proto protoreflect.FileDescriptor

const file_pkg_models_modelspb_models_proto_rawDesc = "" +
	"\n" +
	" pkg/models/modelspb/models.proto\x12\n" +
	"dss.models\x1a\x1fgoogle/protobuf/timestamp.proto\"c\n" +
	"\tCellUnion\x12\x1d\n" +
	"\n" +
	"first_cell\x18\x01 \x01(\x06R\tfirstCell\x12\x1f\n" +
	"\vdelta_shift\x18\x02 \x01(\rR\n" +
	"deltaShift\x12\x16\n" +
	"\x06deltas\x18\x03 \x03(\x12R\x06deltas\"\x9a\x02\n" +
	"\rCellsVolume4D\x12+\n" +
	"\x05cells\x18\x01 \x01(\v2\x15.dss.models.CellUnionR\x05cells\x129\n" +
	"\n" +
	"start_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12$\n" +
	"\valtitude_lo\x18\x04 \x01(\x02H\x00R\n" +
	"altitudeLo\x88\x01\x01\x12$\n" +
	"\valtitude_hi\x18\x05 \x01(\x02H\x01R\n" +
	"altitudeHi\x88\x01\x01B\x0e\n" +
	"\f_altitude_loB\x0e\n" +
	"\f_altitude_hiB-Z+github.com/interuss/dss/pkg/models/modelspbb\x06proto3"

var (
	file_pkg_models_modelspb_models_proto_rawDescOnce sync.Once
	file_pkg_models_modelspb_models_proto_rawDescData []byte
)

func file_pkg_models_modelspb_models_proto_rawDescGZIP() []byte {
	file_pkg_models_modelspb_models_proto_rawDescOnce.Do(func() {
		file_pkg_models_modelspb_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_models_modelspb_models_proto_rawDesc), len(file_pkg_models_modelspb_models_proto_rawDesc)))
	})
	return file_pkg_models_modelspb_models_proto_rawDescData
}

var file_pkg_models_modelspb_models_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_models_modelspb_models_proto_goTypes = []any{
	(*CellUnion)(nil),             // 0: dss.models.CellUnion
	(*CellsVolume4D)(nil),         // 1: dss.models.CellsVolume4D
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_pkg_models_modelspb_models_proto_depIdxs = []int32{
	0, // 0: dss.models.CellsVolume4D.cells:type_name -> dss.models.CellUnion
	2, // 1: dss.models.CellsVolume4D.start_time:type_name -> google.protobuf.Timestamp
	2, // 2: dss.models.CellsVolume4D.end_time:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_models_modelspb_models_proto_init() }
func file_pkg_models_modelspb_models_proto_init() {
	if File_pkg_models_modelspb_models_proto != nil {
		return
	}
	file_pkg_models_modelspb_models_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_models_modelspb_models_proto_rawDesc), len(file_pkg_models_modelspb_models_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_models_modelspb_models_proto_goTypes,
		DependencyIndexes: file_pkg_models_modelspb_models_proto_depIdxs,
		MessageInfos:      file_pkg_models_modelspb_models_proto_msgTypes,
	}.Build()
	File_pkg_models_modelspb_models_proto = out.File
	file_pkg_models_modelspb_models_proto_goTypes = nil
	file_pkg_models_modelspb_models_proto_depIdxs = nil
}
